services:
  react:
    extends:
      file: ../binotify-premium/docker-compose.yml
      service: react
    networks:
      - app-tier
  php:
    extends:
      file: ../binotify-app/docker-compose.yml
      service: php
    networks:
      - app-tier
  php-database:
    extends:
      file: ../binotify-app/docker-compose.yml
      service: php-database
    networks:
      - app-tier
  rest-backend:
    extends:
      file: ../binotify-rest/docker-compose.yml
      service: rest-backend
    networks:
      - app-tier
  rest-database:
    extends:
      file: ../binotify-rest/docker-compose.yml
      service: rest-database
    networks:
      - app-tier
  redis:
    extends:
      file: ../binotify-rest/docker-compose.yml
      service: redis
    networks:
      - app-tier
  soap-service:
    extends:
      file: ../binotify-soap/docker-compose.yml
      service: soap
    networks:
      - app-tier
  soap-database:
    extends:
      file: ../binotify-soap/docker-compose.yml
      service: soap-database
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge